### ISSUE TITLE
doesn't save on edit

### ISSUE THREAD

**Issue by aapocketz** [muhimasri/angular-dynamic-table#1]
I can edit the table, but it doesn't keep the values when you hit done. The binding to the model appears to be read-only making an editable table of questionable value.

**Comment by muhimasri** [comment]
Thanks for opening an issue. This repository was created for the purpose of supporting the article I wrote about dynamic tables and schemas. It was not intended to save the object as this depends on the architecture of your project. Some developers might have immutable objects in a separate layer for saving data. That being said, I updated the repository to edit the object directly when changing a row. Simply replaced (value) with [(ngModel)].
